name: weather_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-89.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  auto_route: ^7.1.0
  get_it: ^7.6.0
  flex_color_scheme: ^7.1.2
  geolocator: ^9.0.2
  http: ^0.13.6
  weather_icons: ^3.0.0
  equatable: ^2.0.5
  dynamic_color: ^1.6.5
  intl: ^0.18.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true